const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');
const dir=path.resolve(__dirname,'../device');
function runtime(){const outputs=[];const context={Math,Date,JSON,isFinite,post(){},outlet(...args){outputs.push(args);}};context.include=name=>vm.runInContext(fs.readFileSync(path.join(dir,name),'utf8'),context);vm.createContext(context);context.include('constellate-engine.js');return {c:context,outputs,bytes(a){a.forEach(n=>context.msg_int(n));},scheduled(){return outputs.filter(a=>a[0]===0);},raw(){return outputs.filter(a=>a[0]===1).map(a=>a[1]);}};}
test('key release does not cancel a pass, and presses stack on separate channels',()=>{const r=runtime();r.bytes([144,60,100,128,60,0,145,64,80]);assert.equal(r.scheduled().length,10);assert.equal(r.scheduled()[0][1][0],1);assert.equal(r.scheduled()[5][1][0],2);assert.equal(r.outputs.filter(a=>a[0]===3).length,0);});
test('running status and zero-velocity note off are handled',()=>{const r=runtime();r.bytes([144,60,100,62,100,60,0]);assert.equal(r.scheduled().length,10);});
test('CC, pitch bend, aftertouch, program change and realtime bytes pass through',()=>{const r=runtime();const bytes=[176,1,64,224,0,64,208,100,192,5,160,60,80,248];r.bytes(bytes);assert.deepEqual(r.raw(),bytes);});
test('system exclusive does not leak data into running note status',()=>{const r=runtime();r.bytes([144,60,100,240,1,2,3,247,60,100]);assert.equal(r.scheduled().length,5);assert.deepEqual(r.raw(),[240,1,2,3,247]);});
test('panic clears native queues and resets sustain; inactive device cannot schedule',()=>{const r=runtime();r.bytes([144,60,100]);r.c.active(0);const count=r.scheduled().length;r.bytes([144,62,100]);assert.equal(r.scheduled().length,count);assert.ok(r.outputs.some(a=>a[0]===3));assert.equal(r.raw().length,48);});
test('transport stop clears tails, while first stopped-state observation is harmless',()=>{const r=runtime();r.c.host('is_playing',0);assert.equal(r.outputs.length,0);r.c.host('is_playing',1);r.c.host('is_playing',0);assert.ok(r.outputs.some(a=>a[0]===3));});
test('density is bounded without stealing playing tails',()=>{const r=runtime();for(let i=0;i<1000;i++)r.bytes([144,60,100]);assert.equal(r.scheduled().length,64*5);});
test('configuration sanitizes parameters and rejects invalid geometry',()=>{const r=runtime();r.c.config('points',10);assert.equal(r.c.geometry.length,10);r.c.shape('not json');r.c.config('strength',0);assert.equal(r.c.settings.strength,0);r.c.trigger(60,100,1);assert.equal(r.scheduled().length,10);});
